from typing import Protocol


class StorageBackend(Protocol):
    async def put(self, key: str, data: bytes) -> None: ...
    async def get(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None: ...
    async def healthcheck(self) -> bool: ...
