/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_v1_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/_schema_probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schema Probe
         * @description Echo the discriminated-union body. SCAFFOLDING — see module docstring.
         */
        post: operations["schema_probe_api_v1__schema_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChoiceBody */
        ChoiceBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "choice";
            /** Choice Values */
            choice_values: string[];
        };
        /** DataEnvelope[Annotated[Union[RichTextBody, ChoiceBody], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]] */
        DataEnvelope_Annotated_Union_RichTextBody__ChoiceBody___FieldInfo_annotation_NoneType__required_True__discriminator__kind____: {
            /** Data */
            data: components["schemas"]["RichTextBody"] | components["schemas"]["ChoiceBody"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[dict[str, object]] */
        DataEnvelope_dict_str__object__: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[dict[str, str]] */
        DataEnvelope_dict_str__str__: {
            /** Data */
            data: {
                [key: string]: string;
            };
            meta?: components["schemas"]["Page"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Page */
        Page: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Per Page
             * @default 25
             */
            per_page: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** RichTextBody */
        RichTextBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rich_text";
            /** Content */
            content: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping_api_v1_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_dict_str__object__"];
                };
            };
        };
    };
    config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_dict_str__str__"];
                };
            };
        };
    };
    schema_probe_api_v1__schema_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RichTextBody"] | components["schemas"]["ChoiceBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_Annotated_Union_RichTextBody__ChoiceBody___FieldInfo_annotation_NoneType__required_True__discriminator__kind____"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
