/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_v1_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_v1_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_v1_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/emergency-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emergency Login */
        post: operations["emergency_login_api_v1_auth_emergency_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_v1_exercises_get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_api_v1_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_v1_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        /** Archive Exercise */
        delete: operations["archive_exercise_api_v1_exercises__exercise_id__delete"];
        options?: never;
        head?: never;
        /** Update Exercise */
        patch: operations["update_exercise_api_v1_exercises__exercise_id__patch"];
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}/team-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Team Types */
        get: operations["list_team_types_api_v1_exercises__exercise_id__team_types_get"];
        put?: never;
        /** Create Team Type */
        post: operations["create_team_type_api_v1_exercises__exercise_id__team_types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}/team-types/{type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Team Type */
        delete: operations["delete_team_type_api_v1_exercises__exercise_id__team_types__type_id__delete"];
        options?: never;
        head?: never;
        /** Update Team Type */
        patch: operations["update_team_type_api_v1_exercises__exercise_id__team_types__type_id__patch"];
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Role Assignments */
        get: operations["list_role_assignments_api_v1_exercises__exercise_id__roles_get"];
        put?: never;
        /** Assign Role */
        post: operations["assign_role_api_v1_exercises__exercise_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}/roles/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Role Assignment */
        delete: operations["remove_role_assignment_api_v1_exercises__exercise_id__roles__assignment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_v1_exercises__exercise_id__teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_api_v1_exercises__exercise_id__teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_api_v1_exercises__exercise_id__teams__team_id__get"];
        put?: never;
        post?: never;
        /** Delete Team */
        delete: operations["delete_team_api_v1_exercises__exercise_id__teams__team_id__delete"];
        options?: never;
        head?: never;
        /** Update Team */
        patch: operations["update_team_api_v1_exercises__exercise_id__teams__team_id__patch"];
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}/teams/{team_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Member */
        post: operations["add_member_api_v1_exercises__exercise_id__teams__team_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/{exercise_id}/teams/{team_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_v1_exercises__exercise_id__teams__team_id__members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_api_v1_roles_get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_api_v1_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Role */
        delete: operations["delete_role_api_v1_roles__role_id__delete"];
        options?: never;
        head?: never;
        /** Update Role */
        patch: operations["update_role_api_v1_roles__role_id__patch"];
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Permissions
         * @description The assignable permission keys, sorted (admin-only; drives the role editor).
         */
        get: operations["list_permissions_api_v1_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_v1_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_api_v1_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_api_v1_templates__template_id__get"];
        put?: never;
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_api_v1_templates__template_id__delete"];
        options?: never;
        head?: never;
        /** Update Template */
        patch: operations["update_template_api_v1_templates__template_id__patch"];
        trace?: never;
    };
    "/api/v1/templates/{template_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Template */
        post: operations["publish_template_api_v1_templates__template_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Template */
        post: operations["clone_template_api_v1_templates__template_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Template */
        post: operations["archive_template_api_v1_templates__template_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Template Versions */
        get: operations["list_template_versions_api_v1_templates__template_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Section */
        post: operations["create_section_api_v1_templates__template_id__sections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}/sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Section */
        delete: operations["delete_section_api_v1_templates__template_id__sections__section_id__delete"];
        options?: never;
        head?: never;
        /** Update Section */
        patch: operations["update_section_api_v1_templates__template_id__sections__section_id__patch"];
        trace?: never;
    };
    "/api/v1/templates/{template_id}/sections/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Sections */
        post: operations["reorder_sections_api_v1_templates__template_id__sections_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Template */
        get: operations["export_template_api_v1_templates__template_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Template */
        post: operations["import_template_api_v1_templates_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/_schema_probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schema Probe
         * @description Echo the discriminated-union body. SCAFFOLDING — see module docstring.
         */
        post: operations["schema_probe_api_v1__schema_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChoiceBody */
        ChoiceBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "choice";
            /** Choice Values */
            choice_values: string[];
        };
        /** DataEnvelope[Annotated[Union[RichTextBody, ChoiceBody], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]] */
        DataEnvelope_Annotated_Union_RichTextBody__ChoiceBody___FieldInfo_annotation_NoneType__required_True__discriminator__kind____: {
            /** Data */
            data: components["schemas"]["RichTextBody"] | components["schemas"]["ChoiceBody"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[ExerciseOut] */
        DataEnvelope_ExerciseOut_: {
            data: components["schemas"]["ExerciseOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[ExerciseRoleOut] */
        DataEnvelope_ExerciseRoleOut_: {
            data: components["schemas"]["ExerciseRoleOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[RoleOut] */
        DataEnvelope_RoleOut_: {
            data: components["schemas"]["RoleOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[SectionOut] */
        DataEnvelope_SectionOut_: {
            data: components["schemas"]["SectionOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[TeamMemberRowOut] */
        DataEnvelope_TeamMemberRowOut_: {
            data: components["schemas"]["TeamMemberRowOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[TeamOut] */
        DataEnvelope_TeamOut_: {
            data: components["schemas"]["TeamOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[TeamTypeConfigOut] */
        DataEnvelope_TeamTypeConfigOut_: {
            data: components["schemas"]["TeamTypeConfigOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[TemplateBundle] */
        DataEnvelope_TemplateBundle_: {
            data: components["schemas"]["TemplateBundle"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[TemplateDetailOut] */
        DataEnvelope_TemplateDetailOut_: {
            data: components["schemas"]["TemplateDetailOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[TemplateOut] */
        DataEnvelope_TemplateOut_: {
            data: components["schemas"]["TemplateOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[TokenResponse] */
        DataEnvelope_TokenResponse_: {
            data: components["schemas"]["TokenResponse"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[UserOut] */
        DataEnvelope_UserOut_: {
            data: components["schemas"]["UserOut"];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[dict[str, bool]] */
        DataEnvelope_dict_str__bool__: {
            /** Data */
            data: {
                [key: string]: boolean;
            };
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[dict[str, object]] */
        DataEnvelope_dict_str__object__: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[dict[str, str]] */
        DataEnvelope_dict_str__str__: {
            /** Data */
            data: {
                [key: string]: string;
            };
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[list[ExerciseOut]] */
        DataEnvelope_list_ExerciseOut__: {
            /** Data */
            data: components["schemas"]["ExerciseOut"][];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[list[ExerciseRoleOut]] */
        DataEnvelope_list_ExerciseRoleOut__: {
            /** Data */
            data: components["schemas"]["ExerciseRoleOut"][];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[list[RoleOut]] */
        DataEnvelope_list_RoleOut__: {
            /** Data */
            data: components["schemas"]["RoleOut"][];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[list[SectionOut]] */
        DataEnvelope_list_SectionOut__: {
            /** Data */
            data: components["schemas"]["SectionOut"][];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[list[TeamOut]] */
        DataEnvelope_list_TeamOut__: {
            /** Data */
            data: components["schemas"]["TeamOut"][];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[list[TeamTypeConfigOut]] */
        DataEnvelope_list_TeamTypeConfigOut__: {
            /** Data */
            data: components["schemas"]["TeamTypeConfigOut"][];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[list[TemplateOut]] */
        DataEnvelope_list_TemplateOut__: {
            /** Data */
            data: components["schemas"]["TemplateOut"][];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[list[TemplateVersionOut]] */
        DataEnvelope_list_TemplateVersionOut__: {
            /** Data */
            data: components["schemas"]["TemplateVersionOut"][];
            meta?: components["schemas"]["Page"] | null;
        };
        /** DataEnvelope[list[str]] */
        DataEnvelope_list_str__: {
            /** Data */
            data: string[];
            meta?: components["schemas"]["Page"] | null;
        };
        /** EmergencyLoginIn */
        EmergencyLoginIn: {
            /** Password */
            password: string;
        };
        /** ExerciseCreate */
        ExerciseCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Starts At */
            starts_at?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /** Classification */
            classification?: string | null;
            /** Tlp */
            tlp?: string | null;
            /** Classification Caveats */
            classification_caveats?: string[] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** ExerciseOut */
        ExerciseOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /** Starts At */
            starts_at: string | null;
            /** Ends At */
            ends_at: string | null;
            /** Classification */
            classification: string | null;
            /** Tlp */
            tlp: string | null;
            /** Classification Caveats */
            classification_caveats: string[] | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Created By */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ExerciseRoleCreate */
        ExerciseRoleCreate: {
            /** User Id */
            user_id: string;
            /** Role Key */
            role_key: string;
        };
        /** ExerciseRoleOut */
        ExerciseRoleOut: {
            /** Id */
            id: string;
            /** Exercise Id */
            exercise_id: string;
            /** User Id */
            user_id: string;
            /** Role Key */
            role_key: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExerciseUpdate */
        ExerciseUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: ("draft" | "active" | "archived") | null;
            /** Starts At */
            starts_at?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /** Classification */
            classification?: string | null;
            /** Tlp */
            tlp?: string | null;
            /** Classification Caveats */
            classification_caveats?: string[] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Page */
        Page: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Per Page
             * @default 25
             */
            per_page: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** ReorderBody */
        ReorderBody: {
            /** Ordered Ids */
            ordered_ids: string[];
        };
        /** RichTextBody */
        RichTextBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rich_text";
            /** Content */
            content: string;
        };
        /** RoleCreate */
        RoleCreate: {
            /** Role Key */
            role_key: string;
            /** Display Label */
            display_label: string;
            /** Description */
            description?: string | null;
            /** Permissions */
            permissions: string[];
        };
        /** RoleOut */
        RoleOut: {
            /** Id */
            id: string;
            /** Role Key */
            role_key: string;
            /** Display Label */
            display_label: string;
            /** Description */
            description: string | null;
            /** Permissions */
            permissions: string[];
            /** Is System */
            is_system: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Display Label */
            display_label?: string | null;
            /** Description */
            description?: string | null;
            /** Permissions */
            permissions?: string[] | null;
        };
        /** SectionCreate */
        SectionCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Field Type
             * @default rich_text
             */
            field_type: string;
            /** Char Limit */
            char_limit?: number | null;
            /**
             * Is Required
             * @default true
             */
            is_required: boolean;
            /**
             * Grade Mode
             * @default not_graded
             */
            grade_mode: string;
            /** Grade Min */
            grade_min?: number | null;
            /** Grade Max */
            grade_max?: number | null;
            /**
             * Grade Weight
             * @default 1
             */
            grade_weight: number;
            /** Rubric Criteria */
            rubric_criteria?: {
                [key: string]: unknown;
            }[] | null;
            /** Evaluation Criteria */
            evaluation_criteria?: string | null;
            /** Choice Config */
            choice_config?: {
                [key: string]: unknown;
            } | null;
            /** Mitre Attack Tags */
            mitre_attack_tags?: string[];
            /** Capec Tags */
            capec_tags?: string[];
            /** Cwe Tags */
            cwe_tags?: string[];
        };
        /** SectionOut */
        SectionOut: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Field Type
             * @default rich_text
             */
            field_type: string;
            /** Char Limit */
            char_limit?: number | null;
            /**
             * Is Required
             * @default true
             */
            is_required: boolean;
            /**
             * Grade Mode
             * @default not_graded
             */
            grade_mode: string;
            /** Grade Min */
            grade_min?: number | null;
            /** Grade Max */
            grade_max?: number | null;
            /**
             * Grade Weight
             * @default 1
             */
            grade_weight: number;
            /** Rubric Criteria */
            rubric_criteria?: {
                [key: string]: unknown;
            }[] | null;
            /** Evaluation Criteria */
            evaluation_criteria?: string | null;
            /** Choice Config */
            choice_config?: {
                [key: string]: unknown;
            } | null;
            /** Mitre Attack Tags */
            mitre_attack_tags?: string[];
            /** Capec Tags */
            capec_tags?: string[];
            /** Cwe Tags */
            cwe_tags?: string[];
            /** Id */
            id: string;
            /** Template Id */
            template_id: string;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SectionUpdate */
        SectionUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Field Type */
            field_type?: string | null;
            /** Char Limit */
            char_limit?: number | null;
            /** Is Required */
            is_required?: boolean | null;
            /** Grade Mode */
            grade_mode?: string | null;
            /** Grade Min */
            grade_min?: number | null;
            /** Grade Max */
            grade_max?: number | null;
            /** Grade Weight */
            grade_weight?: number | null;
            /** Rubric Criteria */
            rubric_criteria?: {
                [key: string]: unknown;
            }[] | null;
            /** Evaluation Criteria */
            evaluation_criteria?: string | null;
            /** Choice Config */
            choice_config?: {
                [key: string]: unknown;
            } | null;
            /** Mitre Attack Tags */
            mitre_attack_tags?: string[] | null;
            /** Capec Tags */
            capec_tags?: string[] | null;
            /** Cwe Tags */
            cwe_tags?: string[] | null;
        };
        /** TeamCreate */
        TeamCreate: {
            /** Name */
            name: string;
            /** Team Type */
            team_type: string;
            /** Color */
            color?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** TeamMemberCreate */
        TeamMemberCreate: {
            /** User Id */
            user_id: string;
        };
        /** TeamMemberOut */
        TeamMemberOut: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TeamMemberRowOut */
        TeamMemberRowOut: {
            /** Id */
            id: string;
            /** Team Id */
            team_id: string;
            /** User Id */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TeamOut */
        TeamOut: {
            /** Id */
            id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Name */
            name: string;
            /** Team Type */
            team_type: string;
            /** Color */
            color: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Members */
            members?: components["schemas"]["TeamMemberOut"][] | null;
        };
        /** TeamTypeConfigCreate */
        TeamTypeConfigCreate: {
            /** Type Key */
            type_key: string;
            /** Display Label */
            display_label: string;
            /** Default Color */
            default_color?: string | null;
            /**
             * Is Visible To Others
             * @default true
             */
            is_visible_to_others: boolean;
        };
        /** TeamTypeConfigOut */
        TeamTypeConfigOut: {
            /** Id */
            id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Type Key */
            type_key: string;
            /** Display Label */
            display_label: string;
            /** Default Color */
            default_color: string | null;
            /** Is Visible To Others */
            is_visible_to_others: boolean;
        };
        /** TeamTypeConfigUpdate */
        TeamTypeConfigUpdate: {
            /** Display Label */
            display_label?: string | null;
            /** Default Color */
            default_color?: string | null;
            /** Is Visible To Others */
            is_visible_to_others?: boolean | null;
        };
        /** TeamUpdate */
        TeamUpdate: {
            /** Name */
            name?: string | null;
            /** Team Type */
            team_type?: string | null;
            /** Color */
            color?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** TemplateBundle */
        TemplateBundle: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Name */
            name: string;
            /** Report Type */
            report_type: string;
            /** Description */
            description?: string | null;
            /** Sections */
            sections: components["schemas"]["SectionCreate"][];
        };
        /** TemplateCreate */
        TemplateCreate: {
            /** Name */
            name: string;
            /** Report Type */
            report_type: string;
            /** Description */
            description?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** TemplateDetailOut */
        TemplateDetailOut: {
            /** Id */
            id: string;
            /** Lineage Id */
            lineage_id: string;
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Report Type */
            report_type: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Sections */
            sections: components["schemas"]["SectionOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TemplateOut */
        TemplateOut: {
            /** Id */
            id: string;
            /** Lineage Id */
            lineage_id: string;
            /** Version */
            version: number;
            /** Name */
            name: string;
            /** Report Type */
            report_type: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /** Section Count */
            section_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TemplateUpdate */
        TemplateUpdate: {
            /** Name */
            name?: string | null;
            /** Report Type */
            report_type?: string | null;
            /** Description */
            description?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** TemplateVersionOut */
        TemplateVersionOut: {
            /** Id */
            id: string;
            /** Version */
            version: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Is Global Admin */
            is_global_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping_api_v1_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_dict_str__object__"];
                };
            };
        };
    };
    config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_dict_str__str__"];
                };
            };
        };
    };
    login_api_v1_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_api_v1_auth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_UserOut_"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_dict_str__bool__"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TokenResponse_"];
                };
            };
        };
    };
    emergency_login_api_v1_auth_emergency_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_api_v1_exercises_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_ExerciseOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_api_v1_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_ExerciseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_api_v1_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_ExerciseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_exercise_api_v1_exercises__exercise_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_ExerciseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_api_v1_exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_ExerciseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_types_api_v1_exercises__exercise_id__team_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_TeamTypeConfigOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_team_type_api_v1_exercises__exercise_id__team_types_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamTypeConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TeamTypeConfigOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_team_type_api_v1_exercises__exercise_id__team_types__type_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_type_api_v1_exercises__exercise_id__team_types__type_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
                type_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamTypeConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TeamTypeConfigOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_role_assignments_api_v1_exercises__exercise_id__roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_ExerciseRoleOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_role_api_v1_exercises__exercise_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_ExerciseRoleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_role_assignment_api_v1_exercises__exercise_id__roles__assignment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_v1_exercises__exercise_id__teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_TeamOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_team_api_v1_exercises__exercise_id__teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TeamOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_api_v1_exercises__exercise_id__teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TeamOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_team_api_v1_exercises__exercise_id__teams__team_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_api_v1_exercises__exercise_id__teams__team_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TeamOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_v1_exercises__exercise_id__teams__team_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamMemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TeamMemberRowOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_exercises__exercise_id__teams__team_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
                team_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_v1_roles_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_RoleOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_role_api_v1_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_RoleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_api_v1_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_v1_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_RoleOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_permissions_api_v1_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_str__"];
                };
            };
        };
    };
    list_templates_api_v1_templates_get: {
        parameters: {
            query?: {
                status?: string | null;
                report_type?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_TemplateOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TemplateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TemplateDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_v1_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_v1_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TemplateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_template_api_v1_templates__template_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TemplateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_template_api_v1_templates__template_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TemplateDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_template_api_v1_templates__template_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TemplateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_template_versions_api_v1_templates__template_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_TemplateVersionOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_section_api_v1_templates__template_id__sections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_SectionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_section_api_v1_templates__template_id__sections__section_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_section_api_v1_templates__template_id__sections__section_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_SectionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_sections_api_v1_templates__template_id__sections_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_list_SectionOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_template_api_v1_templates__template_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TemplateBundle_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_template_api_v1_templates_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateBundle"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_TemplateDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schema_probe_api_v1__schema_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RichTextBody"] | components["schemas"]["ChoiceBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvelope_Annotated_Union_RichTextBody__ChoiceBody___FieldInfo_annotation_NoneType__required_True__discriminator__kind____"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
